src/event_management_system/event_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static

from . import views


urlpatterns = [
    path('', views.index, name="event_management_system_index"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('emails/', include('emails.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/event_management_system/events/urls.py
from django.urls import path

from . import views

urlpatterns = [ 
    # Events
    path('event/', views.event_overview, name='event_overview'),
    path('event/create/', views.event_create, name='event_create'),
    path('event/edit/<int:event_id>/', views.event_edit, name='event_edit'),
    path('event/delete/<int:event_id>/', views.event_delete, name='event_delete'),
    path('event/archive/<int:event_id>/', views.event_archive, name='event_archive'),
    path('event/enable_call_for_papers/<int:event_id>/', views.enable_call_for_papers, name='enable_call_for_papers'),
    path('event/disable_call_for_papers/<int:event_id>/', views.disable_call_for_papers, name='disable_call_for_papers'),
    path('event/<int:event_id>/scheduler/', views.event_scheduler, name='event_scheduler'),

    # Timeslots
    path('event/<int:event_id>/timeslot/', views.event_timeslot, name='event_timeslot'),
    path('event/<int:event_id>/timeslot/add/', views.event_timeslot_add, name='event_timeslot_add'),
    path('event/<int:event_id>/timeslot/remove/<int:index>/', views.event_timeslot_remove, name='event_timeslot_remove'),

    # Custom Questions
    path('event/<int:event_id>/custom_questions/', views.event_custom_questions, name='event_custom_questions'),
    path('event/<int:event_id>/custom_questions/add/', views.event_custom_questions_add, name='event_custom_questions_add'),
    path('event/<int:event_id>/custom_questions/remove/<int:id>', views.event_custom_questions_remove, name='event_custom_questions_remove'),

    # Field Activation
    path('event/<int:event_id>/field_activation/', views.event_field_activation, name='event_field_activation'),

    # Rooms
    path('room/', views.room_overview, name='room_overview'),
    path('room/create/', views.room_create, name='room_create'),
    path('room/edit/<int:room_id>/', views.room_edit, name='room_edit'),
    path('room/delete/<int:room_id>/', views.room_delete, name='room_delete'),

    # Lectures
    path('<int:event_id>/lecture/public/create/entry/', views.lecture_public_create_entry, name = 'lecture_public_create_entry'),
    path('<int:event_id>/lecture/public/create/', views.lecture_public_create, name = 'lecture_public_create'),
    path('<int:event_id>/lecture/public/created_success', views.lecture_public_created_successfully, name = 'lecture_public_created_successfully'),
    path('<int:event_id>/lecture/overview/', views.lecture_overview, name = 'lecture_overview'),
    path('<int:event_id>/lecture/create/', views.lecture_create, name = 'lecture_create'),
    path('lecture/edit/<int:lecture_id>/', views.lecture_edit, name = 'lecture_edit'),
    path('lecture/view/<int:lecture_id>/', views.lecture_view, name = 'lecture_view'),
    path('lecture/delete/<int:lecture_id>/', views.lecture_delete, name = 'lecture_delete'),
    path('lecture/export_csv/', views.lecture_export_csv, name = 'lecture_export_csv'),
    path('<int:event_id>/timetable/', views.timetable, name = 'timetable'),
    path('<int:event_id>/current_running/<int:room_id>/', views.lecture_current_running, name = 'lecture_current_running'),

    # Lectures (contact specific)
    path('lecture/contact/overview', views.lecture_contact_overview, name = 'lecture_contact_overview'),
    path('lecture/contact/create_entry', views.lecture_contact_create_entry, name = 'lecture_contact_create_entry'),
    path('lecture/contact/edit/<int:lecture_id>', views.lecture_contact_edit, name = 'lecture_contact_edit'),
    path('lecture/contact/view/<int:lecture_id>', views.lecture_contact_view, name = 'lecture_contact_view'),

    # Get all Lectures of an event over api:
    path('api/<int:event_id>/', views.api_event_data, name = "api_event_data"),


]

src/event_management_system/users/urls.py
from django.urls import path

from . import views

urlpatterns = [ 
    path('', views.user_overview, name='user_overview'),
    path('delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('create/', views.user_create, name='user_create'),
    path('register/', views.user_register, name='user_register'),
    path('edit/<int:user_id>', views.user_edit, name='user_edit'),
    path('view/<int:user_id>/', views.user_view, name='user_view'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('reset_password/', views.user_reset_password, name='user_reset_password'),
    path('change_password/', views.user_change_password, name='user_change_password'),
    path('edit_profile/', views.user_edit_profile, name='user_edit_profile'),
    path('export_csv/', views.user_export_csv, name='user_export_csv'),

    
]

src/event_management_system/events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

TARGET_GROUP = [
    ('BE', _('Beginner')),
    ('IN', _('Intermediate')),
    ('PR', _('Professional')),
]

PRESENTATION_STYLE = [
    ('RE', _('Recorded')),
    ('LI', _('Live')),
]


class Event(models.Model):
    name = models.CharField(max_length=100)   
    year = models.IntegerField()
    website = models.URLField()
    available_timeslots = models.CharField(max_length=2048, default="")
    call_for_papers = models.BooleanField(default=False)
    custom_questions = models.CharField(max_length=4096, default="")
    disabled_fields = models.CharField(max_length=1024, default="")
    live_board_default = models.CharField(max_length=4096, default="")
    archived = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.name}"

    # TODO TimeSlots (nur Strings :)) 
    # TODO Tracks / Rooms


class Room(models.Model):
    name = models.CharField(max_length=100)
    website = models.URLField()
    coordinates = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.name}"


class Lecture(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    presentator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="presenting")
    attendant = models.ForeignKey(User, on_delete=models.CASCADE, related_name="attending", blank=True, null=True)
    title = models.CharField(max_length=100)   
    description = models.CharField(max_length=2048)   
    target_group = models.CharField(max_length=2, choices=TARGET_GROUP)
    available_timeslots = models.CharField(max_length=2048) # Encoded in JSON
    minimal_lecture_length = models.IntegerField() # (Minutes)
    maximal_lecture_length = models.IntegerField() # (Minutes)
    preferred_presentation_style = models.CharField(max_length=2, choices=PRESENTATION_STYLE)
    qualification_for_lecture = models.CharField(max_length=512)
    questions_during_lecture = models.BooleanField()
    questions_after_lecture = models.BooleanField()
    additional_information_by_presentator = models.CharField(max_length=2048) 
    scheduled_in_room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="held_in", blank=True, null=True)
    scheduled_presentation_time = models.DateTimeField(blank=True, null=True)
    scheduled_presentation_length = models.IntegerField(default=0) # (Minutes)
    scheduled_presentation_style = models.CharField(max_length=2, choices=PRESENTATION_STYLE)
    further_information = models.CharField(max_length=2048) 
    related_website = models.URLField()
    link_to_material = models.URLField()
    link_to_recording = models.URLField()
    custom_question_answers = models.CharField(max_length=4096, default="")
    thumbnail = models.ImageField(upload_to="thumbnails/", null=True, blank=True)


    def __str__(self):
        return f"{self.title}"

src/event_management_system/events/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _



from .models import PRESENTATION_STYLE, TARGET_GROUP, Event, Room


class EventForm(forms.Form):
    name = forms.CharField(label=_('Name'), max_length=100, widget=forms.TextInput(attrs={'class': "form-control"}))
    year = forms.CharField(label=_('Year'), max_length=100, widget=forms.NumberInput(attrs={'class': "form-control"}))
    website = forms.CharField(
        label=_('Website'), max_length=100,
        widget=forms.URLInput(attrs={'class': "form-control"}),
        required=False
    )
    live_board_default = forms.CharField(label=_('Live board default text (supports html, max. 4098 signs)'), max_length=4096, widget=forms.Textarea(attrs={'class': "form-control"}))

class RoomFrom(forms.Form):
    name = forms.CharField(label=_('Name'), max_length=100, widget=forms.TextInput(attrs={'class': "form-control"}))
    website = forms.CharField(
        label=_('Website'), max_length=100,
        widget=forms.URLInput(attrs={'class': "form-control"}),
        required=False
    )
    coordinates = forms.CharField(
        label=_('Coordinates'), max_length=100,
        widget=forms.TextInput(attrs={'class': "form-control"}),
        required=False
    )

class LoginForm(forms.Form):
    email = forms.CharField(label=_('Email'), max_length=100, widget=forms.EmailInput(attrs={'class': "form-control"}))
    password = forms.CharField(
        label=_('Password'), max_length=100,
        widget=forms.PasswordInput(attrs={'class': "form-control"}),
    )


class LectureSubmitForm(forms.Form):
    title = forms.CharField(label=_('Title'), max_length=100, widget=forms.TextInput(attrs={'class': "form-control"}),)
    description = forms.CharField(label=_('Description (max. 2048 signs)'), max_length=2048, widget=forms.Textarea(attrs={'class': "form-control"}),)
    target_group = forms.CharField(label=_('Target Group'), widget=forms.Select(choices=TARGET_GROUP, attrs={'class': "form-control"}))
    qualification_for_lecture = forms.CharField(label=_('I am qualified for the presentation because...'), max_length=100, widget=forms.TextInput(attrs={'class': "form-control"}),)
    preferred_presentation_style = forms.CharField(label=_('Preferred presentation style'), widget=forms.Select(choices=PRESENTATION_STYLE, attrs={'class': "form-select"}))
    questions_during_lecture = forms.BooleanField(label=_('Should questions during lectures been asked?'), widget=forms.CheckboxInput(attrs={'class': "form-check-input"}), required=False)
    questions_after_lecture = forms.BooleanField(label=_('Should questions after lectures been asked?'), widget=forms.CheckboxInput(attrs={'class': "form-check-input"}), required=False)
    minimal_lecture_length = forms.IntegerField(label=_('Minimal Lecture Length (in minutes)'), widget=forms.NumberInput(attrs={'class': "form-control"}),)
    maximal_lecture_length = forms.IntegerField(label=_('Maximal Lecture Length (in minutes)'), widget=forms.NumberInput(attrs={'class': "form-control"}),)
    additional_information_by_presentator = forms.CharField(label=_('Additional information (max. 2048 signs)'), max_length=2048, widget=forms.Textarea(attrs={'class': "form-control"}), required=False)
    related_website = forms.CharField(label=_('Lecture related Website'), max_length=100, widget=forms.URLInput(attrs={'class': "form-control"}), required=False)
    thumbnail = forms.ImageField(label=_('Thumbnail'), required=False)


# For edit and create:
class LectureForm(forms.Form):
    event = forms.ModelChoiceField(label=_("Event"), queryset=Event.objects.all(), widget=forms.Select(attrs={'class': "form-select"}))
    presentator = forms.ModelChoiceField(label=_("Presentator"), queryset=User.objects.all(), widget=forms.Select(attrs={'class': "form-select"}), blank=False)
    attendant = forms.ModelChoiceField(label=_("Attendant"), queryset=User.objects.filter(groups__name='Attendant'), widget=forms.Select(attrs={'class': "form-select"}), required=False, blank=False)
    title = forms.CharField(label=_('Title'), max_length=100, widget=forms.TextInput(attrs={'class': "form-control"}),)
    description = forms.CharField(label=_('Description (max. 2048 signs)'), max_length=2048, widget=forms.Textarea(attrs={'class': "form-control"}),)
    target_group = forms.CharField(label=_('Target Group'), widget=forms.Select(choices=TARGET_GROUP, attrs={'class': "form-control"}))
    qualification_for_lecture = forms.CharField(label=_('I am qualified for the presentation because...'), max_length=100, widget=forms.TextInput(attrs={'class': "form-control"}),)
    preferred_presentation_style = forms.CharField(label=_('Preferred presentation style'), widget=forms.Select(choices=PRESENTATION_STYLE, attrs={'class': "form-select"}))
    questions_during_lecture = forms.BooleanField(label=_('Should questions during lectures been asked?'), widget=forms.CheckboxInput(attrs={'class': "form-check-input"}), required=False)
    questions_after_lecture = forms.BooleanField(label=_('Should questions after lectures been asked?'), widget=forms.CheckboxInput(attrs={'class': "form-check-input"}), required=False)
    minimal_lecture_length = forms.IntegerField(label=_('Minimal Lecture Length (in minutes)'), widget=forms.NumberInput(attrs={'class': "form-control"}),)
    maximal_lecture_length = forms.IntegerField(label=_('Maximal Lecture Length (in minutes)'), widget=forms.NumberInput(attrs={'class': "form-control"}),)
    additional_information_by_presentator = forms.CharField(label=_('Additional information (max. 2048 signs)'), max_length=2048, widget=forms.Textarea(attrs={'class': "form-control"}), required=False)
    related_website = forms.CharField(label=_('Lecture related Website'), max_length=100, widget=forms.URLInput(attrs={'class': "form-control"}), required=False)
    scheduled_in_room = forms.ModelChoiceField(label=_("Scheduled in Room"), queryset=Room.objects.all(), widget=forms.Select(attrs={'class': "form-select"}), required=False)
    scheduled_presentation_time = forms.CharField(label=_("Scheduled Time Format: YYYY-MM-DD HH:MM"), required=False, widget=forms.TextInput(attrs={'class': "form-select"}))
    scheduled_presentation_length = forms.IntegerField(label=_('Scheduled Length (in minutes)'), widget=forms.NumberInput(attrs={'class': "form-control"}), required=False)
    scheduled_presentation_style = forms.CharField(label=_('Scheduled presentation style'), widget=forms.Select(choices=PRESENTATION_STYLE, attrs={'class': "form-select"}), required=False)
    further_information = forms.CharField(label=_('Further private information (max. 2048 signs) (Presentator can\'t see this)'), max_length=2048, widget=forms.Textarea(attrs={'class': "form-control"}), required=False)
    link_to_material = forms.CharField(label=_('Link to Material'), max_length=100, widget=forms.URLInput(attrs={'class': "form-control"}), required=False)
    link_to_recording = forms.CharField(label=_('Link to Recording'), max_length=100, widget=forms.URLInput(attrs={'class': "form-control"}), required=False)
    thumbnail = forms.ImageField(label=_('Thumbnail'), required=False)

src/event_management_system/events/templates/events/lecture/create.html
{% extends "global/base.html" %}
{% load i18n %}
{% block content %}
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
rel="stylesheet">
<script crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
<link rel="stylesheet" href="/static/events/css/bootstrap-datetimepicker.min.css" type="text/css" media="all" />
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
<script type="text/javascript" src="/static/events/js/bootstrap-datetimepicker.min.js"></script>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>{% trans "Create Lecture" %}</h1>
    <br/>
    {% comment %} {{ form }} {% endcomment %}
    {% for field in form %}
        {% if field.name == "questions_during_lecture" %}
        <br>  {{ field }} {{ field.label_tag }}  <br>
        {% elif field.name == "questions_after_lecture" %}
        <br>  {{ field }}  {{ field.label_tag }}  <br> <br>
        {% elif field.name == "scheduled_presentation_time" %}
            {{ field }}
        <div class="form-group">
            <label for="id_scheduled_presentation_time">{{field.label}}:</label>
            <div class="input-group date" id="datetimepicker-1">
                <input type="text" id="datetimepicker-1-input" name="scheduled_presentation_time" value="{{field.data}}" class="form-control" placeholder="" title="" id="id_scheduled_presentation_time"/>
                <div class="input-group-addon input-group-append">
                    <div class="input-group-text">
                        <i class="glyphicon glyphicon-time fa fa-clock-o"></i>
                    </div>
                </div>
            </div>
        </div>
        {% elif field.name == "thumbnail" %}
        <br>
        <div class="input-group mb-3">
            <label class="input-group-text" for="{{field.name}}">Thumbnail</label>
            <input type="file" name="thumbnail" class="form-control" accept="image/*" id="id_thumbnail">
        </div>
        {% else %}
            {{ field.label_tag }} {{ field }}
        {% endif %}
    {% endfor %}
    <br/>

    <script>
        document.getElementById('datetimepicker-1-input').value = document.getElementById('id_scheduled_presentation_time').value
        document.getElementById("id_scheduled_presentation_time").style.display = "none";
        document.getElementById('datetimepicker-1-input').value = document.getElementById('datetimepicker-1-input').value.replace("+00:00", "")
        $('#datetimepicker-1').datetimepicker({
            "allowInputToggle": true,
            "showClose": true,
            "showClear": true,
            "showTodayButton": false,
            "format": "YYYY-MM-DD HH:mm",
        });
    </script>

    {% include "events/modules/timeslot_module.html" %}

    {% include "events/modules/additional_questions_module.html" %}

    <a href="{% url 'lecture_overview' event_id %}"><button type="button" class="btn btn-secondary">Cancel</button></a>
    <input type="submit" value="Create" class="btn btn-primary">
</form>
{% endblock %}

src/event_management_system/events/templates/events/lecture/edit.html
{% extends "global/base.html" %}
{% load i18n %}
{% block content %}
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
rel="stylesheet">
<script crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
<link rel="stylesheet" href="/static/events/css/bootstrap-datetimepicker.min.css" type="text/css" media="all" />
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
<script type="text/javascript" src="/static/events/js/bootstrap-datetimepicker.min.js"></script>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>{% trans "Edit.heading" %} {{lecture.title}}</h1>
    
    {% comment %} Display thumbnail {% endcomment %}
    {% if lecture.thumbnail %}
        <img src="{{ lecture.thumbnail.url }}" class="rounded mx-auto d-block" alt="thumbnail" height="300">
    {% endif %}

    <br/>
    {% comment %} {{ form }} {% endcomment %}
    {% for field in form %}
        {% if field.name == "questions_during_lecture" %}
        <br>  {{ field }} {{ field.label_tag }}  <br>
        {% elif field.name == "questions_after_lecture" %}
        <br>  {{ field }}  {{ field.label_tag }}  <br> <br>
        {% elif field.name == "scheduled_presentation_time" %}
            {{ field }}
        <div class="form-group">
            <label for="id_scheduled_presentation_time">{{field.label}}:</label>
            <div class="input-group date" id="datetimepicker-1">
                <input type="text" id="datetimepicker-1-input" name="scheduled_presentation_time" value="{{field.data}}" class="form-control" placeholder="" title="" id="id_scheduled_presentation_time"/>
                <div class="input-group-addon input-group-append">
                    <div class="input-group-text">
                        <i class="glyphicon glyphicon-time fa fa-clock-o"></i>
                    </div>
                </div>
            </div>
        </div>
        {% elif field.name == "thumbnail" %}
        <br>
        <div class="input-group mb-3">
            <label class="input-group-text" for="{{field.name}}">Thumbnail</label>
            <input type="file" name="thumbnail" class="form-control" accept="image/*" id="id_thumbnail">
        </div>
        {% else %}
            {{ field.label_tag }} {{ field }}
        {% endif %}
    {% endfor %}
    <br/>

    <script>
        document.getElementById('datetimepicker-1-input').value = document.getElementById('id_scheduled_presentation_time').value
        document.getElementById("id_scheduled_presentation_time").style.display = "none";
        document.getElementById('datetimepicker-1-input').value = document.getElementById('datetimepicker-1-input').value.replace("+00:00", "")
        $('#datetimepicker-1').datetimepicker({
            "allowInputToggle": true,
            "showClose": true,
            "showClear": true,
            "showTodayButton": false,
            "format": "YYYY-MM-DD HH:mm",
        });
    </script>
   
   {% include "events/modules/timeslot_module.html" %}

   {% include "events/modules/additional_questions_module.html" %}

    <a href="{% url 'lecture_overview' lecture.event.id %}"><button type="button" class="btn btn-secondary">{% trans "Cancel" %}</button></a>
    <input type="submit" value="{% trans "Save" %}" class="btn btn-primary">
</form>

{% endblock %}

src/event_management_system/events/templates/events/lecture/view.html
{% extends "global/base.html" %}
{% load i18n %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h1>{{lecture.title}}</h1>

    {% comment %} Display thumbnail {% endcomment %}
    {% if lecture.thumbnail %}
        <img src="{{ lecture.thumbnail.url }}" class="rounded mx-auto d-block" alt="thumbnail" height="300">
    {% endif %}


    <br/>
    {% comment %} {{ form }} {% endcomment %}
    {% for field in form %}
        {% if field.name == "questions_during_lecture" %}
        <br>  {{ field }} {{ field.label_tag }}  <br>
        {% elif field.name == "questions_after_lecture" %}
        <br>  {{ field }}  {{ field.label_tag }}  <br> <br>
        {% else %}
            {{ field.label_tag }} {{ field }}
        {% endif %}
    {% endfor %}
    <br/>

    {% include "events/modules/timeslot_module.html" %}

    {% include "events/modules/additional_questions_module.html" %}

    <a href="{% url 'lecture_overview' lecture.event.id %}"><button type="button" class="btn btn-secondary">{% trans "Back" %}</button></a>
</form>
{% endblock %}