src/event_management_system/event_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static

from . import views


urlpatterns = [
    path('', views.index, name="event_management_system_index"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('emails/', include('emails.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/event_management_system/users/urls.py
from django.urls import path

from . import views

urlpatterns = [ 
    path('', views.user_overview, name='user_overview'),
    path('delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('create/', views.user_create, name='user_create'),
    path('register/', views.user_register, name='user_register'),
    path('edit/<int:user_id>', views.user_edit, name='user_edit'),
    path('view/<int:user_id>/', views.user_view, name='user_view'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('reset_password/', views.user_reset_password, name='user_reset_password'),
    path('change_password/', views.user_change_password, name='user_change_password'),
    path('edit_profile/', views.user_edit_profile, name='user_edit_profile'),
    path('export_csv/', views.user_export_csv, name='user_export_csv'),

    
]

src/event_management_system/events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

TARGET_GROUP = [
    ('BE', _('Beginner')),
    ('IN', _('Intermediate')),
    ('PR', _('Professional')),
]

PRESENTATION_STYLE = [
    ('RE', _('Recorded')),
    ('LI', _('Live')),
]


class Event(models.Model):
    name = models.CharField(max_length=100)   
    year = models.IntegerField()
    website = models.URLField()
    available_timeslots = models.CharField(max_length=2048, default="")
    call_for_papers = models.BooleanField(default=False)
    custom_questions = models.CharField(max_length=4096, default="")
    disabled_fields = models.CharField(max_length=1024, default="")
    live_board_default = models.CharField(max_length=4096, default="")
    archived = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.name}"

    # TODO TimeSlots (nur Strings :)) 
    # TODO Tracks / Rooms


class Room(models.Model):
    name = models.CharField(max_length=100)
    website = models.URLField()
    coordinates = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.name}"


class Lecture(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    presentator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="presenting")
    attendant = models.ForeignKey(User, on_delete=models.CASCADE, related_name="attending", blank=True, null=True)
    title = models.CharField(max_length=100)   
    description = models.CharField(max_length=2048)   
    target_group = models.CharField(max_length=2, choices=TARGET_GROUP)
    available_timeslots = models.CharField(max_length=2048) # Encoded in JSON
    minimal_lecture_length = models.IntegerField() # (Minutes)
    maximal_lecture_length = models.IntegerField() # (Minutes)
    preferred_presentation_style = models.CharField(max_length=2, choices=PRESENTATION_STYLE)
    qualification_for_lecture = models.CharField(max_length=512)
    questions_during_lecture = models.BooleanField()
    questions_after_lecture = models.BooleanField()
    additional_information_by_presentator = models.CharField(max_length=2048) 
    scheduled_in_room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="held_in", blank=True, null=True)
    scheduled_presentation_time = models.DateTimeField(blank=True, null=True)
    scheduled_presentation_length = models.IntegerField(default=0) # (Minutes)
    scheduled_presentation_style = models.CharField(max_length=2, choices=PRESENTATION_STYLE)
    further_information = models.CharField(max_length=2048) 
    related_website = models.URLField()
    link_to_material = models.URLField()
    link_to_recording = models.URLField()
    custom_question_answers = models.CharField(max_length=4096, default="")
    thumbnail = models.ImageField(upload_to="thumbnails/", null=True, blank=True)


    def __str__(self):
        return f"{self.title}"

src/event_management_system/users/models.py
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import string
import random

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField()
    company = models.CharField(max_length=100)
    over_18 = models.BooleanField()
    private_pin = models.CharField(max_length=100) # Second password/pin for e.g. doors or jitsi

    image = models.ImageField(upload_to='profile_pics', blank=True, null=True)
    vita = models.CharField(max_length=2048, blank=True, null=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            profile = Profile(user=instance)
            profile.over_18 = True
            profile.save()


    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return f"{self.user.email} - {self.user.last_name} - {self.company}"

    def getUserRoleOfString(user_role_string):
        if user_role_string == 'CO':
            return Profile.UserRole.CONTACT
        elif user_role_string == 'AT':
            return Profile.UserRole.ATTENDANT
        elif user_role_string == 'OR':
            return Profile.UserRole.ORGANISATOR
        elif user_role_string == 'AD':
            return Profile.UserRole.ADMIN
        else:
            print(f"ERROR: getUserRoleOfString: no defined UserRole for {user_role_string}")
            return "Unknown!"

    def reset_password(self):
        characters = list(string.ascii_letters + string.digits + "!@#$%^&*()")
        
        password = []
        for i in range(20):
            password.append(random.choice(characters))

        random.shuffle(password)
        password_string = "".join(password)
        self.user.set_password(password_string)
        self.user.save()
        return password_string

src/event_management_system/event_management_system/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import redirect

from . import set_rights


def index(request):
    set_rights.init()
    if User.objects.count() == 0:
        return HttpResponseRedirect("/users/register/?next=/")
    if not request.user.is_authenticated:
        return redirect('user_login')
    if request.user.groups.filter(name='Contact').exists():
        return redirect('lecture_contact_overview')
    return redirect('event_overview')

src/event_management_system/event_management_system/templates/global/base.html
{% load i18n %}
<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% trans "Event Management System" %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">  </head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <style>
      .table > tbody > tr > td {
        vertical-align: middle;
      }
      .table > tbody > tr > th {
        vertical-align: middle;
      }
    </style>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    {% include 'global/navbar.html' %} 
    <br/>
    <br/>

    <div class="container">
  
        {% block content %}
        {% endblock %}

        <br>
        <br>
  
    </div>
  </body>
</html>

src/event_management_system/event_management_system/templates/global/base_public.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if automatic_refresh %}
      <meta http-equiv="refresh" content="{{automatic_refresh}}">
    {% endif %}
    <title>Event Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">  </head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <style>
      .table > tbody > tr > td {
        vertical-align: middle;
      }
      .table > tbody > tr > th {
        vertical-align: middle;
      }
    </style>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <br/>
    <br/>

    <div class="container-fluid">
  
        {% block content %}
        {% endblock %}
  
        <br>
        <br>

    </div>
  </body>
</html>

src/event_management_system/event_management_system/templates/global/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'user_overview' %}">Event Management System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if perms.users.view_profile %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'user_overview' %}">{% trans "Users" %}</a>
          </li>
          {% endif %}
          {% if perms.events.view_event %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'event_overview' %}">{% trans "Events" %}</a>
          </li>
          {% endif %}
          {% if perms.events.view_room %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'room_overview' %}">{% trans "Rooms" %}</a>
          </li>
          {% endif %}
          {% if perms.emails.view_email %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'email_overview' %}">{% trans "Emails" %}</a>
            </li>
          {% endif %}
        </ul>

          {% if request_user.is_authenticated %}
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{request_user.username}}
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'user_edit_profile' %}">{% trans "Edit Profile" %}</a></li>
              <li><a class="dropdown-item" href="{% url 'user_change_password' %}">{% trans "Change Password" %}</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'user_logout' %}">{% trans "Logout" %}</a></li>
              {% endif %}
            </ul>
          </div>


      </div>
    </div>
  </nav>